<html>
<head>
<title>Exceptional Code: Using try-except in Python</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">异常代码:在Python中使用try-except</h1>
<blockquote>原文：<a href="https://betterprogramming.pub/exceptional-code-using-try-except-in-python-540b6416db79?source=collection_archive---------11-----------------------#2020-01-07">https://betterprogramming.pub/exceptional-code-using-try-except-in-python-540b6416db79?source=collection_archive---------11-----------------------#2020-01-07</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="7460" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">Python中异常的处理与其他一些语言略有不同。那么，我们何时以及如何使用try-except呢？</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/d41faa504f1cf4694ba37ca6aeac4e74.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*TGdmCdDp60I8hHpzSLAqNg.jpeg"/></div></div><p class="kr ks gj gh gi kt ku bd b be z dk translated">里克·桑切斯在<a class="ae kv" href="https://unsplash.com/s/photos/exceptional?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的照片</p></figure></div><div class="ab cl kw kx hu ky" role="separator"><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb"/></div><div class="ij ik il im in"><h1 id="12a6" class="ld le iq bd lf lg lh li lj lk ll lm ln jw lo jx lp jz lq ka lr kc ls kd lt lu bi translated">快速介绍</h1><p id="078b" class="pw-post-body-paragraph lv lw iq lx b ly lz jr ma mb mc ju md me mf mg mh mi mj mk ml mm mn mo mp mq ij bi translated">如果您曾经对如何或何时使用Python中的try-except块感到困惑，您并不孤单。让我们看看什么是try-except，什么时候使用它最好，以及我们如何在Python中使用它。</p><p id="1cc1" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">首先，让我们快速思考一下<em class="mw">异常</em>这个词是什么意思。在字典中，它被定义为:</p><blockquote class="mx"><p id="89ee" class="my mz iq bd na nb nc nd ne nf ng mq dk translated"><strong class="ak">/ɪkˈsɛpʃ(ə)n,ɛkˈsɛpʃ(ə)n/</strong>——被排除在一般陈述之外或不遵守规则的人或事。</p></blockquote><p id="ad68" class="pw-post-body-paragraph lv lw iq lx b ly nh jr ma mb ni ju md me nj mg mh mi nk mk ml mm nl mo mp mq ij bi translated">同样，在编程的环境中:</p><blockquote class="mx"><p id="4bc2" class="my mz iq bd na nb nc nd ne nf ng mq dk translated"><strong class="ak">异常</strong>是在执行<strong class="ak">程序</strong>期间发生的事件，它扰乱了正常的指令流。</p></blockquote></div><div class="ab cl kw kx hu ky" role="separator"><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb"/></div><div class="ij ik il im in"><h1 id="ca62" class="ld le iq bd lf lg lh li lj lk ll lm ln jw lo jx lp jz lq ka lr kc ls kd lt lu bi translated">Python中的异常</h1><p id="35a9" class="pw-post-body-paragraph lv lw iq lx b ly lz jr ma mb mc ju md me mf mg mh mi mj mk ml mm mn mo mp mq ij bi translated">程序员处理异常的方式取决于他们所使用的语言的文化规范，以及他们所选择的语言的异常处理程序的工作和执行方式。</p><p id="804c" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">经常有一些相当激烈的建议，关于<em class="mw">永远不要</em>使用try-except，除非是灾难性的、低级别的事件，并确保将所有其他事情隔离到传统的流控制中(例如if-else)——这在许多语言中都是正确的。</p><p id="b3b7" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">在Python中，事情有点不同。尽管我们需要对它的正确使用保持敏感，但使用try是一种正常且相当常见的做法——除了流控制，这是Python核心中常用的一种模式。</p><p id="e2d5" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">也就是说，我们不应该过度使用它，寻找大量使用它的机会，或者在try-except块中包装长的应用程序代码块(原因我们将很快介绍)。</p><p id="a4e7" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">但是，重要的是，在Python中，我们不需要害怕使用try——除了管理某些事件——特别是如果它们可以调用不可忽略的结果，并且可以在适当的时候帮助干净地管理程序的主流程。</p></div><div class="ab cl kw kx hu ky" role="separator"><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb"/></div><div class="ij ik il im in"><h1 id="5c76" class="ld le iq bd lf lg lh li lj lk ll lm ln jw lo jx lp jz lq ka lr kc ls kd lt lu bi translated">那么，我们如何使用try-except？</h1><p id="29f5" class="pw-post-body-paragraph lv lw iq lx b ly lz jr ma mb mc ju md me mf mg mh mi mj mk ml mm mn mo mp mq ij bi translated">在我们编写try-catch块之前，我们想问:</p><ul class=""><li id="5eef" class="nm nn iq lx b ly mr mb ms me no mi np mm nq mq nr ns nt nu bi translated">我们认为这里会出什么问题？</li><li id="6497" class="nm nn iq lx b ly nv mb nw me nx mi ny mm nz mq nr ns nt nu bi translated">我们可以向开发者或用户返回哪些有用的信息？</li><li id="2757" class="nm nn iq lx b ly nv mb nw me nx mi ny mm nz mq nr ns nt nu bi translated">我们如何确保不泄露太多信息，并保持安全？</li></ul><h2 id="3c3f" class="oa le iq bd lf ob oc dn lj od oe dp ln me of og lp mi oh oi lr mm oj ok lt ol bi translated">一个工作实例</h2><p id="c900" class="pw-post-body-paragraph lv lw iq lx b ly lz jr ma mb mc ju md me mf mg mh mi mj mk ml mm mn mo mp mq ij bi translated">一个好的常见用例是从外部源请求数据，比如API端点。</p><p id="7b1c" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">让我们举一个假设的例子——我们正在使用伦敦的<a class="ae kv" href="https://api.tfl.gov.uk/" rel="noopener ugc nofollow" target="_blank"> TFL API </a>为伦敦皮卡迪利广场的公交车站构建一个数字到达板！</p><p id="0ec5" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">为此，我们需要ping Piccadilly Circus stop point API端点，使用其适当的端点:<a class="ae kv" href="https://api.tfl.gov.uk/StopPoint/490000179F/arrivals" rel="noopener ugc nofollow" target="_blank">https://api.tfl.gov.uk/StopPoint/490000179F/arrivals</a>，以JSON格式返回其即将到来的到达。</p><p id="85ae" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">如果没有成功返回的数据内容，我们的数字公交站牌根本做不了什么。</p><p id="a372" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">这个API调用是一个潜在的破坏点——它是我们无法控制的第三方资源，有时，它可能会经历意外的停机时间。那么，如果它关闭了，我们的代码会发生什么呢？</p><p id="8554" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">使用try-catch，我们可以简单地确保一个坏的响应不会破坏我们的程序，通过编写:</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="om on l"/></div></figure><p id="66d9" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">(更好的是，在这个实例中，我们实际上使用了Requests库中内置的<code class="fe oo op oq or b">raise_for_status</code>函数<strong class="lx ir"> </strong>，它将自动为我们捕捉任何HTTP问题，并很好地精简我们的代码。)</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="om on l"/></div></figure><h2 id="07c9" class="oa le iq bd lf ob oc dn lj od oe dp ln me of og lp mi oh oi lr mm oj ok lt ol bi translated">好吧，那么什么是"<em class="os">其他"</em>？</h2><p id="db3a" class="pw-post-body-paragraph lv lw iq lx b ly lz jr ma mb mc ju md me mf mg mh mi mj mk ml mm mn mo mp mq ij bi translated">在一个try-except块中使用<code class="fe oo op oq or b">else:</code>的一个有用之处就是稍微美化了一下我们的代码。</p><p id="50f2" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">这意味着我们可以在相同的缩进层次上可视化地对齐异常和常规操作的结果，而不是超越下面的指令。</p><p id="5d76" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">(这种特殊的用法是可选的，严格来说不是必需的，但是从结构上来说，感觉很有条理，所以很好。)</p><h2 id="91af" class="oa le iq bd lf ob oc dn lj od oe dp ln me of og lp mi oh oi lr mm oj ok lt ol bi translated"><code class="fe oo op oq or b">And, "finally"...</code></h2><p id="0e5f" class="pw-post-body-paragraph lv lw iq lx b ly lz jr ma mb mc ju md me mf mg mh mi mj mk ml mm mn mo mp mq ij bi translated"><code class="fe oo op oq or b">finally:</code>在尝试结束时执行——除了在<strong class="lx ir">所有情况下</strong> <em class="mw"> — </em>即使前一行用<em class="mw"> return </em>语句求值。</p><p id="633a" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">要小心这一点——它用于不管块中其他任何东西而发生的事情。</p><p id="69a5" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">例如，这对于关闭打开的文件是很有用的，这样当你移动到下一个操作时，不管结果如何，你都不会不小心让它们打开。</p></div><div class="ab cl kw kx hu ky" role="separator"><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb lc"/><span class="kz bw bk la lb"/></div><div class="ij ik il im in"><h1 id="9d12" class="ld le iq bd lf lg lh li lj lk ll lm ln jw lo jx lp jz lq ka lr kc ls kd lt lu bi translated">所以，一般来说</h1><ul class=""><li id="aadc" class="nm nn iq lx b ly lz mb mc me ot mi ou mm ov mq nr ns nt nu bi translated">不要害怕——但是要仔细思考并战略性地使用它。</li><li id="f6a7" class="nm nn iq lx b ly nv mb nw me nx mi ny mm nz mq nr ns nt nu bi translated">避免包装大块代码——这是因为您需要将一个<code class="fe oo op oq or b">try</code>隔离到一个特定的调用或动作，该调用或动作可能会产生一个单一的、不可忽略的结果，从而使您能够<code class="fe oo op oq or b">catch</code>那个特定的异常。如果您将一组不同的任务打包到一个try中，那么您可能会在代码中引发异常，而这些代码本来就不应该受到保护。这很笨拙，会导致意外的副作用，并且在调试时令人头疼。</li><li id="021a" class="nm nn iq lx b ly nv mb nw me nx mi ny mm nz mq nr ns nt nu bi translated">千万不要把它们当作if/else语句使用— <strong class="lx ir"> </strong>出于上述原因，大多数时候，你会希望使用if/else语句，尤其是在设计你的主要流控制时。</li></ul><p id="87a3" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">编码快乐！</p><p id="7bb8" class="pw-post-body-paragraph lv lw iq lx b ly mr jr ma mb ms ju md me mt mg mh mi mu mk ml mm mv mo mp mq ij bi translated">托马斯·卡尔</p></div></div>    
</body>
</html>