<html>
<head>
<title>To Throw or Not to Throw? Error Propagation in JavaScript and TypeScript</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">扔还是不扔？JavaScript和TypeScript中的错误传播</h1>
<blockquote>原文：<a href="https://betterprogramming.pub/to-throw-or-not-to-throw-error-propagation-in-js-and-ts-68aaabe30e30?source=collection_archive---------2-----------------------#2022-10-01">https://betterprogramming.pub/to-throw-or-not-to-throw-error-propagation-in-js-and-ts-68aaabe30e30?source=collection_archive---------2-----------------------#2022-10-01</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="e9d3" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">探索误差传播原理</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/4467ec40b1280de022ceeae6db41e679.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*ZdBz_Rz9lU6Jbyt0"/></div></div><p class="kr ks gj gh gi kt ku bd b be z dk translated">莎拉·基利安在<a class="ae kv" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的照片</p></figure><p id="28ef" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">JavaScript和TypeScript中最有问题的概念之一是错误传播。问题的一部分是对异常和错误之间的区别的误解。</p><p id="3aab" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">这篇文章旨在发现异常类型并定义错误传播原则。尽管本文强调了JavaScript和TypeScript，但同样的错误传播原则也适用于许多其他语言。</p><h1 id="d619" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">异常和错误</h1><p id="a742" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">错误是一个对象，它包含关于什么地方出错了以及在代码中什么地方出错的信息。异常不是错误；<a class="ae kv" href="https://en.wikipedia.org/wiki/Exception_handling" rel="noopener ugc nofollow" target="_blank"> <em class="mp">异常</em> </a> <em class="mp"> </em>是需要特殊处理的异常或例外情况。这种情况有两种:<em class="mp">运行</em>和<em class="mp">非运行</em>。</p><p id="85a6" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">输入验证错误为<em class="mp">操作</em>错误<em class="mp">。</em>失败的登录尝试是一种<em class="mp">操作</em>情况。这些用例是预期的，并得到相应的处理。每当出现这种情况时，应用程序都会照常运行。</p><p id="e378" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">不可操作的条件是应用程序不能自动解决错误，应该被终止。例如，应用程序应该将数据存储在数据库中。当无法连接到数据库时，应用程序的某些功能会丢失。如果该功能是关键的，则应用处于<em class="mp">非操作</em>状态。如果它不能自动恢复，应该终止它。</p><h1 id="1a80" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">误差传播</h1><p id="66b5" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">一切都从错误传播开始。返回错误的方法决定了应用程序是继续运行还是最好停止。错误传播方法还定义了应该如何处理错误。</p><p id="bece" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在JavaScript和TypeScript中有两种传播错误的方法:</p><ul class=""><li id="4da0" class="mq mr iq ky b kz la lc ld lf ms lj mt ln mu lr mv mw mx my bi translated"><a class="ae kv" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw" rel="noopener ugc nofollow" target="_blank">抛出</a>异常。如果不处理，它将终止进程。当打算在出错时停止应用程序时，应该使用它。</li><li id="36da" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">返回一个错误。它表示预期的错误情况，不需要应用程序终止。</li></ul><p id="6e0f" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">使用<em class="mp"> throw </em>机制返回错误的危险在于，如果处理不当，它可能会终止应用程序。仅仅返回错误不会停止应用程序。但是忽略这样的错误会将应用程序带入一种意想不到的无序状态。</p><p id="dd45" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">选择错误传播机制的另一个重要方面是文档。使用TypeScript时，语言服务会推断函数的输入和输出参数的类型。如果函数返回一个错误类型的参数，它在代码编辑器中是可见的，并降低了丢失错误处理的风险。当函数抛出异常时，情况就不同了——语言服务无法识别它。在<a class="ae kv" href="https://tsdoc.org/" rel="noopener ugc nofollow" target="_blank"> TSDoc </a>中定义了<a class="ae kv" href="https://tsdoc.org/pages/tags/throws/" rel="noopener ugc nofollow" target="_blank"> <em class="mp"> throws </em> </a> <em class="mp"> </em>标签，但是并没有广泛使用。发现函数抛出异常的唯一方法是阅读它的源代码。</p><h1 id="07ed" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">异常处理</h1><p id="b6dd" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">异常处理取决于错误的返回方式和返回错误的函数类型。对于同步函数来说相对容易。当被函数返回时，用<em class="mp"> if </em>子句检查错误。如果一个函数抛出异常，它的调用通常由<em class="mp"> try/catch </em>保护。</p><p id="3f44" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在异步函数的情况下，异常处理更加复杂。有几种方法可以处理异步操作:</p><ul class=""><li id="3444" class="mq mr iq ky b kz la lc ld lf ms lj mt ln mu lr mv mw mx my bi translated">使用回调函数</li><li id="a7f5" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">使用带有<code class="fe ne nf ng nh b">.then</code>和<code class="fe ne nf ng nh b">.catch</code>的承诺</li><li id="d585" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">用<code class="fe ne nf ng nh b">await</code>来解决承诺</li></ul><p id="3b85" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">还有发电机，我就省略了。</p><p id="e3a6" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">回调中的异常处理非常简单。每当一个异步操作完成时，操作处理程序调用一个回调函数并返回错误(如果有的话)。按照惯例，回调函数的第一个参数是一个错误。如果错误不为空，回调函数调用将停止。这使得控制流易于理解。</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="ni nj l"/></div></figure><p id="2afe" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">这里有一些挑战。不清楚错误是由<em class="mp">操作</em>还是<em class="mp">非操作</em>异常引起的。另一个挑战是处理结果传播。将一个函数的输出传递给另一个函数的输入的需求产生了大量带有嵌套回调的代码，很难阅读和维护。</p><p id="3b65" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">Promises解决了编排函数的顺序调用(同步和异步)的问题。一系列的承诺可以和<em class="mp">的一个电话联系在一起。然后，</em>和数据可以在调用之间流动。但是承诺使用回调并继承了相同的异常处理挑战。</p><p id="9efe" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated"><em class="mp"> Async/await </em>消除了使用回调的需要，解决了编排问题。现在可以等待异步函数的结果了。它让代码更干净、更易读，至少是一条<em class="mp">快乐之路</em>。<em class="mp"> Try/catch </em>取代了回调错误处理技术。一开始感觉像是赢了。事实上，新问题取代了旧问题:</p><ul class=""><li id="189f" class="mq mr iq ky b kz la lc ld lf ms lj mt ln mu lr mv mw mx my bi translated">当使用<em class="mp"> try/catch、</em>保护异步函数调用时，仍然不清楚错误是由<em class="mp">操作性</em>还是<em class="mp">非操作性</em>异常导致的。</li><li id="3b39" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">在一个<em class="mp"> try/catch </em>块中看到多个异步函数调用并不少见。在这种情况下，<em class="mp"> catch </em>子句处理所有函数的异常。在<em class="mp"> catch </em>块中看到复杂的错误处理逻辑，试图理解什么函数调用是错误的来源，这种情况并不少见。</li><li id="5b22" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">嵌套的<em class="mp"> try/catch </em>块。它看起来甚至比嵌套回调更糟糕。</li></ul><p id="9e39" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">那么，我们如何在异步调用编排中利用<em class="mp"> async/await </em>的优势，并最小化异常处理问题呢？</p><h1 id="f9d0" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">错误传播和处理原则</h1><ul class=""><li id="853e" class="mq mr iq ky b kz mk lc ml lf nk lj nl ln nm lr mv mw mx my bi translated"><em class="mp">操作</em>异常返回错误。</li><li id="bf45" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">总是检查返回的错误。</li><li id="929f" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">对于<em class="mp">非操作性</em>异常抛出错误。</li><li id="6f31" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated"><em class="mp">试</em>语句块应该守护单个逻辑单元或一个调用。</li><li id="8699" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">避免在<em class="mp"> catch </em>子句中使用复杂的逻辑。</li><li id="b277" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">不要嵌套<em class="mp">试/抓</em>块。</li><li id="95f5" class="mq mr iq ky b kz mz lc na lf nb lj nc ln nd lr mv mw mx my bi translated">换行错误。</li></ul><p id="7dea" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">包装错误意味着接受一个错误值，并将另一个错误值放入其中。它允许用关于错误来自哪里或如何发生的附加信息来扩展错误，而不会丢失原始值。有几个<a class="ae kv" href="https://2ality.com/2021/06/error-cause.html#a-library" rel="noopener ugc nofollow" target="_blank">库</a>支持JavaScript中的错误包装。或者，您可以采用ECMAScript2022，它内置了对<code class="fe ne nf ng nh b"><a class="ae kv" href="https://2ality.com/2022/06/ecmascript-2022.html#error.cause" rel="noopener ugc nofollow" target="_blank">error.cause</a></code> <em class="mp">的支持。</em></p><p id="23f9" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">以下部分显示了错误传播和处理的示例:</p><h2 id="2e1d" class="nn lt iq bd lu no np dn ly nq nr dp mc lf ns nt me lj nu nv mg ln nw nx mi ny bi translated">尝试捕捉方法</h2><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="ni nj l"/></div></figure><p id="500c" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">当<em class="mp"> try/catch </em>守护单个语句时，很容易推断出代码。当需要处理多个异步调用时，情况会变得更糟。</p><h2 id="4f07" class="nn lt iq bd lu no np dn ly nq nr dp mc lf ns nt me lj nu nv mg ln nw nx mi ny bi translated">包装尝试/捕捉方法</h2><p id="1ed9" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">这种方法在函数中隐藏了<em class="mp"> try/catch </em>。函数声明声明它可以返回一个错误或一个值。它允许使用一个<em class="mp"> if </em>语句来控制逻辑流程。</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="ni nj l"/></div></figure><p id="db73" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">下面的例子是概括错误处理的下一步。它使用TypeScript实用工具类型来推断函数参数和输出类型。</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="ni nj l"/></div></figure><p id="1d56" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">上面的例子使用了<a class="ae kv" href="https://deno.land/" rel="noopener ugc nofollow" target="_blank"> Deno </a> read file API。要运行它们，请使用以下命令:</p><pre class="kg kh ki kj gt nz nh oa ob aw oc bi"><span id="03c4" class="nn lt iq nh b gy od oe l of og">$ FILE=hello.txt deno run --allow-env=FILE --allow-read main.ts</span></pre></div><div class="ab cl oh oi hu oj" role="separator"><span class="ok bw bk ol om on"/><span class="ok bw bk ol om on"/><span class="ok bw bk ol om"/></div><div class="ij ik il im in"><p id="36eb" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">感谢阅读。</p></div></div>    
</body>
</html>